In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression

In [24]:
data = pd.read_csv('1.02. Multiple linear regression.csv')
x = data[['SAT', 'Rand 1,2,3']]
y = data['GPA']

In [25]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

In [26]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

### R-Square     

In [27]:
reg.score(x,y)

0.4066811952814285

### Coef

In [28]:
reg.coef_

array([ 0.00165354, -0.00826982])

### Intercept

In [29]:
reg.intercept_

0.29603261264909486

In [34]:
reg.predict([[1700,3]])

array([3.08224421])

In [32]:
new_data = pd.DataFrame(data = [[1740,2],[1760,3]], columns = ['SAT','Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1740           2
1  1760           3

In [127]:
reg.predict(new_data)

array([3.15593751, 3.18905127])

In [33]:
new_data['Predicted_GPA'] = reg.predict(new_data)
new_data

SAT  Rand 1,2,3  Predicted_GPA
0  1740           2       3.156656
1  1760           3       3.181457

In [129]:
#ArithmeticErrorreg.predict(x_matrix)

In [35]:
entire_data = pd.DataFrame(data = x, columns = ['SAT','Rand 1,2,3'])
entire_data

SAT  Rand 1,2,3
0   1714           1
1   1664           3
2   1760           3
3   1685           3
4   1693           2
..   ...         ...
79  1936           3
80  1810           1
81  1987           3
82  1962           1
83  2050           2

[84 rows x 2 columns]

In [36]:
entire_data['Predict GPA'] = reg.predict(x)
entire_data

SAT  Rand 1,2,3  Predict GPA
0   1714           1     3.121933
1   1664           3     3.022717
2   1760           3     3.181457
3   1685           3     3.057441
4   1693           2     3.078939
..   ...         ...          ...
79  1936           3     3.472480
80  1810           1     3.280673
81  1987           3     3.556811
82  1962           1     3.532012
83  2050           2     3.669254

[84 rows x 3 columns]

### Adjusted R-Squared
$R^2_{adj.} = 1 - (1-R^2)*\frac{n-1}{n-p-1}$

In [38]:
r2 = reg.score(x,y)

n = x.shape[0]

p = x.shape[1]

In [39]:
r2_adj = 1 - (1-r2)*(n-1)/(n-p-1)
r2_adj

0.39203134825134023